@startuml

title "Component Diagram of JaPong"

package Server {
    folder "Process" as serverProcess {
        [Game State Management]
        interface "Command" as GamaStateManagementCommand
        [Game State Management] -- GamaStateManagementCommand
        [Room Management]
        interface "Request" as RoomManagementCommand
        [Room Management] -- RoomManagementCommand
    }
}

package Client {
    folder "Process" as clientProcess {
        [Rendering] -right- UI
        [Game State Management] -down-> UI
        [Room Management] - UI
        [User Input] -up-> GamaStateManagementCommand
        [User Input] -up-> RoomManagementCommand
    }
}

@enduml