@startuml

title "Timing Diagtam of Pong++"

robust Server
Concise Client

@0
Server is State0
Client is Idle

@10
Server -> Client@+10: UI

@30
Client is Right
Client -> Server@+10: Right

@40
Client -> Server@+10: Right

@50
Client -> Server@+10: Right

@60
Server is State1
Client -> Server@+10: Right

@70
Server -> Client@+10: UI
Client is Left
Client -> Server@+10: Left

@80
Client -> Server@+10: Left

@90
Client -> Server@+10: Left

@100
Client is Right
Client -> Server@+10: Right

@110
Client -> Server@+10: Right

@120
Server is State2
Client is Idle

@130
Server -> Client@+10: UI

@140
@enduml