name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of my repository to the ubuntu machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          VALIDATE_CSS: false
          VALIDATE_HTML: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSON: false
          DEFAULT_BRANCH: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
